// Entities: unit definitions and factories
const unitDefs = {
  Warrior: {
    hp: 6,
    range: 1,
    dmg: 3,
    move: 2,
    cost: 2,
    symbol: "⚔️",
    ability: "Tough melee",
    rangePattern: "orthogonal",
    movePattern: "orthogonal",
    cooldowns: { "Charge": 2 }
  },
  Archer: {
    hp: 6,
    range: 3,
    dmg: 3,
    move: 1,
    cost: 4,
    symbol: "🏹",
    ability: "Long range",
    rangePattern: "straight",
    movePattern: "orthogonal",
    cooldowns: { "Snipe": 2 }
  },
  Mage: {
    hp: 5,
    range: 2,
    dmg: 2,
    move: 1,
    cost: 2,
    symbol: "🔮",
    ability: "Frostbolt (Damage + Stun)",
    rangePattern: "square",
    movePattern: "orthogonal",
    cooldowns: { "Frostbolt": 2 }
  },
  Paladin: {
    hp: 8,
    range: 2,
    dmg: 4,
    move: 2,
    cost: 5,
    symbol: "🛡️",
    ability: "Smite distant foe",
    rangePattern: "orthogonal",
    movePattern: "orthogonal",
    cooldowns: { "Smite": 2 }
  },
  Berserker: {
    hp: 7,
    range: 2,
    dmg: 3,
    move: 3,
    cost: 3,
    symbol: "🪓",
    ability: "Whirlwind attack",
    rangePattern: "orthogonal",
    movePattern: "orthogonal",
    cooldowns: { "Whirlwind": 2 }
  },
  Builder: {
    hp: 5,
    range: 2,
    dmg: 2,
    move: 2,
    cost: 2,
    symbol: "🛠️",
    ability: "Construct or clear terrain",
    rangePattern: "orthogonal",
    movePattern: "orthogonal",
    cooldowns: { "Construct": 2 }
  },
  Alchemist: {
    hp: 6,
    range: 3,
    dmg: 3,
    move: 2,
    cost: 5,
    symbol: "⚗️",
    ability: "Catalyze a 3x3 area",
    rangePattern: "thrower",
    movePattern: "square",
    cooldowns: { "Catalyze": 2 }
  },
  Rogue: {
    hp: 5,
    range: 1,
    dmg: 4,
    move: 2,
    cost: 3,
    symbol: "🗡️",
    ability: "Shadow Strike (Teleport + Dmg)",
    rangePattern: "orthogonal",
    movePattern: "orthogonal",
    cooldowns: { "Shadow Strike": 2 }
  },
  Cleric: {
    hp: 6,
    range: 2,
    dmg: 2,
    move: 2,
    cost: 4,
    symbol: "⚕️",
    ability: "Mass Heal adjacent allies",
    rangePattern: "square",
    movePattern: "orthogonal",
    cooldowns: { "Mass Heal": 2 }
  },
  Firecaller: {
    hp: 6,
    range: 3,
    dmg: 2,
    move: 2,
    cost: 4,
    symbol: "🔥",
    ability: "Ignite 3x3 area (burn)",
    rangePattern: "square",
    movePattern: "orthogonal",
    cooldowns: { "Ignite": 3 }
  },
  Magnet: {
    hp: 8,
    range: 1,
    dmg: 4,
    move: 2,
    cost: 5,
    symbol: "🧲",
    ability: "Pull units toward self",
    rangePattern: "square",
    movePattern: "orthogonal",
    cooldowns: { "Pull": 2 }
  },
  Avenger: {
    hp: 7,
    range: 2,
    dmg: 2,
    move: 2,
    cost: 3,
    symbol: "🦅",
    ability: "Gain +1 DMG/HP/Max HP per ally death",
    rangePattern: "orthogonal",
    movePattern: "orthogonal"
  },
  Necromancer: {
    hp: 5,
    range: 2,
    dmg: 2,
    move: 2,
    cost: 5,
    symbol: "☠️",
    ability: "Raise 3 skeletons in a 3x3 area",
    rangePattern: "square",
    movePattern: "orthogonal",
    cooldowns: { "Raise Dead": 3 }
  },
  Skeleton: {
    hp: 1,
    range: 1,
    dmg: 1,
    move: 2,
    symbol: "💀",
    ability: "Summoned minion",
    rangePattern: "orthogonal",
    movePattern: "orthogonal",
    hiddenFromShop: true
  },
};

const makeBase = (team, row, col) => ({
  kind: "base",
  team,
  row,
  col,
  hp: 20,
  maxHp: 20,
  symbol: team === "P" ? "🏰" : "⛩️",
});

const makeUnit = (team, type, row, col) => ({
  kind: "unit",
  team,
  type,
  row,
  col,
  hp: unitDefs[type].hp,
  maxHp: unitDefs[type].hp,
  range: unitDefs[type].range,
  dmg: unitDefs[type].dmg,
  move: unitDefs[type].move,
  symbol: unitDefs[type].symbol,
  ability: unitDefs[type].ability,
  rangePattern: unitDefs[type].rangePattern,
  movePattern: unitDefs[type].movePattern || "orthogonal",
  abilityCooldowns: {},
  runes: [],
  exp: 0,
  level: 1,
  apMax: 2,
  ap: 2,
  stunnedTurns: 0,
});

window.Entities = { unitDefs, makeBase, makeUnit };
