const unitDefs = {};
const biomeDefs = {};

const makeBase = (team, row, col) => ({
  kind: "base",
  team,
  row,
  col,
  hp: 200,
  maxHp: 200,
  symbol: team === "P" ? "🏰" : "⛩️",
});

const makeUnit = (team, type, row, col) => ({
  kind: "unit",
  team,
  type,
  row,
  col,
  hp: unitDefs[type].hp,
  maxHp: unitDefs[type].hp,
  range: unitDefs[type].range,
  dmg: unitDefs[type].dmg,
  move: unitDefs[type].move,
  symbol: unitDefs[type].symbol,
  ability: unitDefs[type].ability,
  rangePattern: unitDefs[type].rangePattern,
  thrower: !!(unitDefs[type] && unitDefs[type].thrower),
  movePattern: unitDefs[type].movePattern || "orthogonal",
  abilityCooldowns: {},
  cooldownMods: {},
  globalCooldownMod: 0,
  runes: [],
  apMax: unitDefs[type].apMax || 2,
  ap: unitDefs[type].apMax || 2,
  stunnedTurns: 0,
  silencedTurns: 0,
  hexTurns: 0,
  diseasedTurns: 0,
  burnTurns: 0,
  beastTurns: 0,
  guardTurns: 0,
  guardValue: unitDefs[type] && unitDefs[type].guardValue != null ? unitDefs[type].guardValue : 0,
  siegeTurns: 0,
  stuck: false,
  waterWalker: unitDefs[type] && !!unitDefs[type].waterWalker,
  inShadowRealm: false,
  shadowTurns: 0,
  diseased: false,
  diseaseSourceTeam: null,
  avengerConsumedDeaths: 0,
  isBeast: false,
});

window.Entities = { unitDefs, biomeDefs, makeBase, makeUnit };
